Feature/interpret templatefile func
tenable/terrascan pull request #1301
Opened 2022-06-24 03:22 UTC by gaurav-gogia

- update converter structure to include module file path
- create a new file `eval-tf-functions`
- interpet terrform's filesystem info variables
- interpret terraform's `templatefile` function

2022-06-29 13:19 UTC, Rchanger reviewed
There is a test failure. Please take a look

2022-06-29 13:43 UTC, patilpankaj212 commented
@gaurav-gogia 
I tried your PR with example in issue https://github.com/tenable/terrascan/issues/1073, I see below error -

```
failed to read template file: read .: is a directory
2022-06-29T19:08:58.804+0530	error	commons/resource.go:50	failed to convert hcl.Body to go struct; resource 'task', file: '/Users/pankajpatil/go/src/bitbucket.org/tcs-demo-resources/gaurav-test/main.tf'. error: 'failed to read template file: read .: is a directory'
```

2022-06-29 14:11 UTC, gaurav-gogia commented
@Rchanger @patilpankaj212 

yes, i must have made some mistakes in `templatefile` function evaluation, will look into them.

2022-06-30 10:05 UTC, Rchanger requested changes
Let's add some e2e tests also

2022-07-08 09:48 UTC, closed without merging